### ISSUE TITLE
PRÁCTICA-ARCHITECT

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-3-practica-architect-yanet-02#1]
[Practica-Diagrama de clase Yanet Gonzalez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-yanet-02/files/12555096/Practica-Diagrama.de.clase.Yanet.Gonzalez.pdf)

**Comment by Luz1727** [comment]
calificación 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
